if __package__ in {None, ""}:
    import importlib.machinery
    import sys
    from pathlib import Path

    __package__ = "digital_drn"
    __path__ = [str(Path(__file__).resolve().parent)]
    __spec__ = importlib.machinery.ModuleSpec("digital_drn", globals().get("__loader__"), is_package=True)
    __spec__.submodule_search_locations = __path__
    sys.modules.setdefault("digital_drn", sys.modules[__name__])

from .app.cli import main as cli_main
from .blocks import (
    BlockFreeCache,
    DigitalDRNBlock,
    build_conv_dense_drn_block,
    build_conv_drn_block,
    build_dense_drn_block,
)
from .core import (
    Bias,
    ConvLayer,
    ConvResistive,
    ConvWeight,
    DenseResistive,
    DenseWeight,
    LinearLayer,
    NonlinearResistiveLayer,
    QuadraticMinimizer,
)
from .energy import (
    AugmentedFunction,
    BaseBlockEnergy,
    ConvDRNBlockEnergy,
    ConvDenseDRNBlockEnergy,
    DenseDRNBlockEnergy,
    FFCurrentInteraction,
    Nudging,
)
from .frontends import MirrorSignedDriveFrontend, build_default_dense_ff, wrap_mirror_signed_drive_frontend
from .models import (
    CausalSelfAttention,
    CrossEntropyReadoutHead,
    DRNGPTConfig,
    DRNTransformerBlock,
    DigitalAnalogNet,
    DigitalClassifierHead,
    DigitalGPTConfig,
    DigitalDRNNet,
    DigitalModuleBlock,
    LayerNorm,
    ResistiveTrainableModel,
    SmallDRNGPT,
    SmallDigitalGPT,
    SequentialDigitalDRNNet,
    TokenwiseDRNMLP,
    build_head_from_spec,
    build_layers_from_spec,
)
from .training import (
    BPTrainer,
    BlockBackwardResult,
    BlockEPResult,
    BlockEquilibriumProp,
    DigitalVJPResult,
    EpochMetrics,
    ExperimentBundle,
    HeadBackwardResult,
    HybridEPTrainer,
    HybridBackwardResult,
    IGNORE_INDEX,
    MQARConfig,
    MQARDataset,
    NetworkFreeCache,
    OptimizerConfig,
    SchedulerConfig,
    SmallGPTMQARDataset,
    TrainHistory,
    TrainerConfig,
    TransformerDRNBlockEPDiagnostic,
    TransformerEPDiagnostic,
    build_dataloaders_from_config,
    build_experiment,
    build_mqar_dataloaders,
    build_model_from_config,
    build_trainer_config_from_config,
    build_trainer_from_config,
    backward_head,
    forward_free_with_cache,
    generate_mqar_batch,
    generate_small_gpt_mqar,
    hybrid_backward_explicit,
    load_experiment_config,
    mqar_config_from_mapping,
    run_mnist_backprop_smoke,
    transformer_drn_ep_diagnostic,
    vjp_ff_block,
)
from .utils import build_image_transforms, resolve_device, set_seed

__all__ = [
    "AugmentedFunction",
    "BPTrainer",
    "BaseBlockEnergy",
    "Bias",
    "BlockBackwardResult",
    "BlockEPResult",
    "BlockEquilibriumProp",
    "BlockFreeCache",
    "CausalSelfAttention",
    "ConvDenseDRNBlockEnergy",
    "ConvDRNBlockEnergy",
    "ConvLayer",
    "ConvResistive",
    "ConvWeight",
    "CrossEntropyReadoutHead",
    "DRNGPTConfig",
    "DRNTransformerBlock",
    "DenseDRNBlockEnergy",
    "DenseResistive",
    "DenseWeight",
    "DigitalVJPResult",
    "DigitalAnalogNet",
    "DigitalClassifierHead",
    "DigitalGPTConfig",
    "DigitalDRNBlock",
    "DigitalDRNNet",
    "DigitalModuleBlock",
    "EpochMetrics",
    "ExperimentBundle",
    "FFCurrentInteraction",
    "HeadBackwardResult",
    "HybridEPTrainer",
    "HybridBackwardResult",
    "IGNORE_INDEX",
    "MQARConfig",
    "MQARDataset",
    "LayerNorm",
    "LinearLayer",
    "MirrorSignedDriveFrontend",
    "NetworkFreeCache",
    "NonlinearResistiveLayer",
    "Nudging",
    "OptimizerConfig",
    "QuadraticMinimizer",
    "ResistiveTrainableModel",
    "SchedulerConfig",
    "SmallGPTMQARDataset",
    "SmallDRNGPT",
    "SmallDigitalGPT",
    "SequentialDigitalDRNNet",
    "TokenwiseDRNMLP",
    "TrainHistory",
    "TrainerConfig",
    "TransformerDRNBlockEPDiagnostic",
    "TransformerEPDiagnostic",
    "build_conv_dense_drn_block",
    "build_conv_drn_block",
    "build_dataloaders_from_config",
    "build_default_dense_ff",
    "build_dense_drn_block",
    "build_experiment",
    "build_head_from_spec",
    "build_image_transforms",
    "build_layers_from_spec",
    "build_mqar_dataloaders",
    "build_model_from_config",
    "build_trainer_config_from_config",
    "build_trainer_from_config",
    "backward_head",
    "cli_main",
    "forward_free_with_cache",
    "generate_mqar_batch",
    "generate_small_gpt_mqar",
    "hybrid_backward_explicit",
    "load_experiment_config",
    "mqar_config_from_mapping",
    "resolve_device",
    "run_mnist_backprop_smoke",
    "set_seed",
    "transformer_drn_ep_diagnostic",
    "vjp_ff_block",
    "wrap_mirror_signed_drive_frontend",
]
