defaults:
  - algorithm: bp
  - trainer: default
  - data: cifar10
  - model: cifar10_drn_only_signed_norm_readout
  - _self_

config:
  device: "cuda"
  save: true
  seed: 0
  deterministic: false
  logger: null
  project_name: "digital_drn"
  output_dir: "simulation_results"

trainer:
  epochs: 100
  optimizer:
    lr: 1.0e-3
  log_every: 10

data:
  config:
    train_subset: 128
    test_subset: 128

model:
  name: "cifar10_drn_only_signed_norm_readout_wider_bp_highlr_overfit"

  config:
    learn_drive_scale: true

  blocks_config:
    - ff:
        type: "digital_conv_block"
        lr: 1.0e-2
        signed_drive: true
        layers:
          - op: "batchnorm2d"
            num_features: 3
        output_shape: [3, 32, 32]

      drn:
        type: "conv_drn_block"
        lr: 1.0e-3
        num_layers: 3
        state_shape: [6, 32, 32]
        channels: [6, 32, 64]
        kernel_size: 3
        stride: 1
        padding: 1
        use_batchnorm: false
        use_pooling: false
        preserve_resolution: true
        weight_gains: [1.0, 1.0]
        bias_gain: 0.0
        weight_min: 1.0e-7
        weight_max: 10.0
        num_iterations: 6

    - ff:
        type: "digital_transition_block"
        lr: 1.0e-2
        signed_drive: true
        transition_option: "A"
        layers:
          - op: "batchnorm2d"
            num_features: 64
          - op: "maxpool2d"
            kernel_size: 2
            stride: 2
        output_shape: [64, 16, 16]

      drn:
        type: "conv_drn_block"
        lr: 1.0e-3
        num_layers: 3
        state_shape: [128, 16, 16]
        channels: [128, 256, 512]
        kernel_size: 3
        stride: 1
        padding: 1
        use_batchnorm: false
        use_pooling: false
        preserve_resolution: true
        weight_gains: [1.0, 1.0]
        bias_gain: 0.0
        weight_min: 1.0e-7
        weight_max: 10.0
        num_iterations: 6

  head:
    type: "digital_classifier_head"
    lr: 3.0e-3
    layers:
      - op: "maxpool2d"
        kernel_size: 2
        stride: 2
      - op: "flatten"
      - op: "linear"
        in_features: 32768
        out_features: 256
      - op: "tanh"
      - op: "linear"
        in_features: 256
        out_features: 10
